mission_id: CRAWL-20250818-001
title: Mapeamento Massivo - Compras Públicas RN
objective: licitacoes
topics:
  - licitacoes
  - compras
  - contratos
entities:
  - tipo: estado
    nome: Rio Grande do Norte
    sigla: RN
constraints:
  require_topic_match: true
  allowed_suffixes:
    - .rn.gov.br
    - .rn.gov
  per_host_cap: 500
  max_pages_per_seed: 1000
seeds:
  - https://www.rn.gov.br
  - https://www.afonsobezerra.rn.gov.br
  - https://afonsobezerra.rn.gov.br
  - https://www.alminoafonso.rn.gov.br
  - https://alminoafonso.rn.gov.br
  - https://www.altodorodrigues.rn.gov.br
  - https://altodorodrigues.rn.gov.br
  - https://www.angicos.rn.gov.br
  - https://www.antoniomartins.rn.gov.br
  - https://angicos.rn.gov.br
  - https://www.aguanova.rn.gov.br
  - https://aguanova.rn.gov.br
  - https://apodi.rn.gov.br
  - https://www.apodi.rn.gov.br
  - https://alexandria.rn.gov.br
  - https://www.areiabranca.rn.gov.br
  - https://areiabranca.rn.gov.br
  - https://antoniomartins.rn.gov.br
  - https://www.alexandria.rn.gov.br
  - https://www.baiaformosa.rn.gov.br
  - https://www.barauna.rn.gov.br
  - https://baiaformosa.rn.gov.br
  - https://barauna.rn.gov.br
  - https://www.acari.rn.gov.br
  - https://acari.rn.gov.br
  - https://www.bentofernandes.rn.gov.br
  - https://www.campogrande.rn.gov.br
  - https://bentofernandes.rn.gov.br
  - https://campogrande.rn.gov.br
  - https://www.barcelona.rn.gov.br
  - https://www.bodo.rn.gov.br
  - https://bodo.rn.gov.br
  - https://barcelona.rn.gov.br
  - https://www.brejinho.rn.gov.br
  - https://brejinho.rn.gov.br
  - https://www.bomjesus.rn.gov.br
  - https://caicaradonorte.rn.gov.br
  - https://www.caicaradonorte.rn.gov.br
  - https://www.camporedondo.rn.gov.br
  - https://caicaradoriodovento.rn.gov.br
  - https://camporedondo.rn.gov.br
  - https://caraubas.rn.gov.br
  - https://www.caraubas.rn.gov.br
  - https://www.caicaradoriodovento.rn.gov.br
  - https://caico.rn.gov.br
  - https://www.caico.rn.gov.br
  - https://www.carnaubais.rn.gov.br
  - https://carnaubais.rn.gov.br
  - https://www.carnaubadosdantas.rn.gov.br
  - https://cearamirim.rn.gov.br
  - https://canguaretama.rn.gov.br
  - https://carnaubadosdantas.rn.gov.br
  - https://www.canguaretama.rn.gov.br
  - https://www.cearamirim.rn.gov.br
  - https://bomjesus.rn.gov.br
  - https://www.cerrocora.rn.gov.br
  - https://cerrocora.rn.gov.br
  - https://coroneljoaopessoa.rn.gov.br
  - https://www.coroneljoaopessoa.rn.gov.br
  - https://cruzeta.rn.gov.br
  - https://coronelezequiel.rn.gov.br
  - https://www.curraisnovos.rn.gov.br
  - https://www.cruzeta.rn.gov.br
  - https://curraisnovos.rn.gov.br
  - https://doutorseveriano.rn.gov.br
  - https://www.doutorseveriano.rn.gov.br
  - https://encanto.rn.gov.br
  - https://www.equador.rn.gov.br
  - https://www.encanto.rn.gov.br
  - https://equador.rn.gov.br
  - https://parnamirim.rn.gov.br
  - https://www.parnamirim.rn.gov.br
  - https://www.espiritosanto.rn.gov.br
  - https://www.fernandopedroza.rn.gov.br
  - https://www.coronelezequiel.rn.gov.br
  - https://espiritosanto.rn.gov.br
  - https://fernandopedroza.rn.gov.br
  - https://florania.rn.gov.br
  - https://extremoz.rn.gov.br
  - https://www.extremoz.rn.gov.br
  - https://www.franciscodantas.rn.gov.br
  - https://franciscodantas.rn.gov.br
  - https://www.florania.rn.gov.br
  - https://galinhos.rn.gov.br
  - https://frutuosogomes.rn.gov.br
  - https://www.goianinha.rn.gov.br
  - https://www.galinhos.rn.gov.br
  - https://www.frutuosogomes.rn.gov.br
  - https://goianinha.rn.gov.br
  - https://guamare.rn.gov.br
  - https://www.grossos.rn.gov.br
  - https://ielmomarinho.rn.gov.br
  - https://www.guamare.rn.gov.br
  - https://grossos.rn.gov.br
  - https://www.ipanguacu.rn.gov.br
  - https://www.ielmomarinho.rn.gov.br
  - https://www.itaja.rn.gov.br
  - https://itaja.rn.gov.br
  - https://ipanguacu.rn.gov.br
  - https://www.ipueira.rn.gov.br
  - https://ipueira.rn.gov.br
  - https://www.itau.rn.gov.br
  - https://itau.rn.gov.br
  - https://www.janduis.rn.gov.br
  - https://jandaira.rn.gov.br
  - https://janduis.rn.gov.br
  - https://www.jardimdeangicos.rn.gov.br
  - https://jacana.rn.gov.br
  - https://japi.rn.gov.br
  - https://www.jacana.rn.gov.br
  - https://jardimdeangicos.rn.gov.br
  - https://www.jandaira.rn.gov.br
  - https://www.jardimdepiranhas.rn.gov.br
  - https://www.japi.rn.gov.br
  - https://jardimdepiranhas.rn.gov.br
  - https://felipeguerra.rn.gov.br
  - https://www.felipeguerra.rn.gov.br
  - https://www.jardimdoserido.rn.gov.br
  - https://jardimdoserido.rn.gov.br
  - https://lagoadanta.rn.gov.br
  - https://www.lagoadanta.rn.gov.br
  - https://jundia.rn.gov.br
  - https://www.lagoanova.rn.gov.br
  - https://lagoanova.rn.gov.br
  - https://www.lagoasalgada.rn.gov.br
  - https://lagoasalgada.rn.gov.br
  - https://www.lajespintadas.rn.gov.br
  - https://www.jundia.rn.gov.br
  - https://lajespintadas.rn.gov.br
  - https://www.luisgomes.rn.gov.br
  - https://luisgomes.rn.gov.br
  - https://www.lucrecia.rn.gov.br
  - https://lucrecia.rn.gov.br
  - https://lagoadevelhos.rn.gov.br
  - https://macaiba.rn.gov.br
  - https://www.macaiba.rn.gov.br
  - https://www.lagoadevelhos.rn.gov.br
  - https://www.lajes.rn.gov.br
  - https://lajes.rn.gov.br
  - https://joaodias.rn.gov.br
  - https://www.joaodias.rn.gov.br
  - https://www.majorsales.rn.gov.br
  - https://majorsales.rn.gov.br
  - https://marcelinovieira.rn.gov.br
  - https://www.macau.rn.gov.br
  - https://macau.rn.gov.br
  - https://www.martins.rn.gov.br
  - https://www.marcelinovieira.rn.gov.br
  - https://martins.rn.gov.br
  - https://messiastargino.rn.gov.br
  - https://www.messiastargino.rn.gov.br
  - https://montanhas.rn.gov.br
  - https://www.montanhas.rn.gov.br
  - https://montealegre.rn.gov.br
  - https://www.montealegre.rn.gov.br
  - https://josedapenha.rn.gov.br
  - https://www.josedapenha.rn.gov.br
  - https://www.maxaranguape.rn.gov.br
  - https://maxaranguape.rn.gov.br
  - https://mossoro.rn.gov.br
  - https://joaocamara.rn.gov.br
  - https://www.nisiafloresta.rn.gov.br
  - https://montedasgameleiras.rn.gov.br
  - https://nisiafloresta.rn.gov.br
  - https://www.natal.rn.gov.br
  - https://novacruz.rn.gov.br
  - https://natal.rn.gov.br
  - https://www.olhodaguadoborges.rn.gov.br
  - https://olhodaguadoborges.rn.gov.br
  - https://www.novacruz.rn.gov.br
  - https://parana.rn.gov.br
  - https://parazinho.rn.gov.br
  - https://parau.rn.gov.br
  - https://www.parau.rn.gov.br
  - https://www.ourobranco.rn.gov.br
  - https://www.parana.rn.gov.br
  - https://www.parazinho.rn.gov.br
  - https://ourobranco.rn.gov.br
  - https://riodofogo.rn.gov.br
  - https://www.riodofogo.rn.gov.br
  - https://www.joaocamara.rn.gov.br
  - https://parelhas.rn.gov.br
  - https://www.parelhas.rn.gov.br
  - https://passaefica.rn.gov.br
  - https://www.patu.rn.gov.br
  - https://www.passaefica.rn.gov.br
  - https://www.pedragrande.rn.gov.br
  - https://www.pedrapreta.rn.gov.br
  - https://pedragrande.rn.gov.br
  - https://www.paudosferros.rn.gov.br
  - https://pedrapreta.rn.gov.br
  - https://paudosferros.rn.gov.br
  - https://www.passagem.rn.gov.br
  - https://patu.rn.gov.br
  - https://passagem.rn.gov.br
  - https://www.pendencias.rn.gov.br
  - https://pendencias.rn.gov.br
  - https://www.piloes.rn.gov.br
  - https://piloes.rn.gov.br
  - https://www.portodomangue.rn.gov.br
  - https://www.santamaria.rn.gov.br
  - https://www.jucurutu.rn.gov.br
  - https://santamaria.rn.gov.br
  - https://www.portalegre.rn.gov.br
  - https://portodomangue.rn.gov.br
  - https://www.pedrovelho.rn.gov.br
  - https://pedrovelho.rn.gov.br
  - https://www.pedroavelino.rn.gov.br
  - https://pedroavelino.rn.gov.br
  - https://portalegre.rn.gov.br
  - https://www.serracaiada.rn.gov.br
  - https://www.pureza.rn.gov.br
  - https://www.rafaelfernandes.rn.gov.br
  - https://www.rafaelgodeiro.rn.gov.br
  - https://pureza.rn.gov.br
  - https://rafaelfernandes.rn.gov.br
  - https://rafaelgodeiro.rn.gov.br
  - https://www.riachodacruz.rn.gov.br
  - https://serracaiada.rn.gov.br
  - https://www.riachodesantana.rn.gov.br
  - https://riachodesantana.rn.gov.br
  - https://www.riachuelo.rn.gov.br
  - https://riachodacruz.rn.gov.br
  - https://www.rodolfofernandes.rn.gov.br
  - https://rodolfofernandes.rn.gov.br
  - https://riachuelo.rn.gov.br
  - https://pocobranco.rn.gov.br
  - https://www.santacruz.rn.gov.br
  - https://santacruz.rn.gov.br
  - https://www.santanadomatos.rn.gov.br
  - https://santanadomatos.rn.gov.br
  - https://lagoadepedras.rn.gov.br
  - https://jucurutu.rn.gov.br
  - https://santoantonio.rn.gov.br
  - https://www.saobentodonorte.rn.gov.br
  - https://saobentodonorte.rn.gov.br
  - https://tibau.rn.gov.br
  - https://www.ruybarbosa.rn.gov.br
  - https://www.tibau.rn.gov.br
  - https://saofernando.rn.gov.br
  - https://www.saofernando.rn.gov.br
  - https://ruybarbosa.rn.gov.br
  - https://www.saofranciscodooeste.rn.gov.br
  - https://www.lagoadepedras.rn.gov.br
  - https://saojoaodosabugi.rn.gov.br
  - https://saofranciscodooeste.rn.gov.br
  - https://www.saojoaodosabugi.rn.gov.br
  - https://www.saomigueldogostoso.rn.gov.br
  - https://www.saopaulodopotengi.rn.gov.br
  - https://saopaulodopotengi.rn.gov.br
  - https://www.saojosedoserido.rn.gov.br
  - https://www.saomiguel.rn.gov.br
  - https://saomiguel.rn.gov.br
  - https://saojosedoserido.rn.gov.br
  - https://saorafael.rn.gov.br
  - https://saopedro.rn.gov.br
  - https://saomigueldogostoso.rn.gov.br
  - https://www.saotome.rn.gov.br
  - https://saotome.rn.gov.br
  - https://www.saorafael.rn.gov.br
  - https://www.saovicente.rn.gov.br
  - https://saovicente.rn.gov.br
  - https://www.saopedro.rn.gov.br
  - https://www.senadoreloidesouza.rn.gov.br
  - https://serradomel.rn.gov.br
  - https://senadoreloidesouza.rn.gov.br
  - https://www.serradomel.rn.gov.br
  - https://www.serrinha.rn.gov.br
  - https://www.sitionovo.rn.gov.br
  - https://severianomelo.rn.gov.br
  - https://www.severianomelo.rn.gov.br
  - https://www.taboleirogrande.rn.gov.br
  - https://serrinha.rn.gov.br
  - https://www.serrinhadospintos.rn.gov.br
  - https://serradesaobento.rn.gov.br
  - https://serrinhadospintos.rn.gov.br
  - https://www.serradesaobento.rn.gov.br
  - https://sitionovo.rn.gov.br
  - https://taboleirogrande.rn.gov.br
  - https://www.taipu.rn.gov.br
  - https://taipu.rn.gov.br
  - https://www.tangara.rn.gov.br
  - https://tangara.rn.gov.br
  - https://www.tenenteananias.rn.gov.br
  - https://www.tibaudosul.rn.gov.br
  - https://tibaudosul.rn.gov.br
  - https://tenenteananias.rn.gov.br
  - https://tenentelaurentinocruz.rn.gov.br
  - https://www.tenentelaurentinocruz.rn.gov.br
  - https://www.upanema.rn.gov.br
  - https://upanema.rn.gov.br
  - https://www.varzea.rn.gov.br
  - https://www.venhaver.rn.gov.br
  - https://venhaver.rn.gov.br
  - https://www.triunfopotiguar.rn.gov.br
  - https://triunfopotiguar.rn.gov.br
  - https://varzea.rn.gov.br
  - https://www.timbaubadosbatistas.rn.gov.br
  - https://timbaubadosbatistas.rn.gov.br
  - https://saojosedocampestre.rn.gov.br
  - https://www.vicosa.rn.gov.br
  - https://vicosa.rn.gov.br
  - https://www.umarizal.rn.gov.br
  - https://touros.rn.gov.br
  - https://umarizal.rn.gov.br
  - https://www.veracruz.rn.gov.br
  - https://www.touros.rn.gov.br
  - https://www.vilaflor.rn.gov.br
  - https://vilaflor.rn.gov.br
  - https://www.saojosedocampestre.rn.gov.br
  - https://veracruz.rn.gov.br
  - https://saojosedemipibu.rn.gov.br
  - https://www.saojosedemipibu.rn.gov.br
notes:
  "Esta missão é destinada a uma varredura em larga escala. Os seeds devem ser
  populados com domínios oficiais dos municípios e secretarias do RN antes da execução.

  Recomenda-se executar primeiro em modo `--dry-run` para validar saída e manifestos,
  depois em modo normal com monitoramento.

  "
